version: '2'
services:
  mysql.dev:
    build:
     context: ../../containers/mysql
     args:
      - AMBARI_DDL_URL=${AMBARI_DDL_URL}
    image: hdp/mysql
    networks:
     - dev

    environment:
     - AMBARI_DDL_URL=${AMBARI_DDL_URL}
     - MYSQL_ROOT_PASSWORD=password
    hostname: mysql
    domainname: dev
  ambari-server.dev:
    build: 
      context: ../../containers/ambari-server
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
    image: hdp/ambari-server

    networks:
     - dev
    hostname: ambari-server
    domainname: dev
    ports:
     - "8080:8080"
    depends_on:
     - mysql.dev
  dn0.dev:
    build:
      context: ../../containers/node
      args:
       - AMBARI_REPO_URL=${AMBARI_REPO_URL}
       - HDP_REPO_URL=${HDP_REPO_URL}
    image: hdp/node
    privileged: true
    networks:
     - dev
    hostname: dn0
    domainname: dev

    ports:
     # Accumulo
     - "50095:50095"
     # Atlas
     - "21000:21000"
     # ZooKeeper
     - "2181:2181"
     # HDFS
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # HDFS
     - "50070:50070"
     - "50470:50470"
     - "50075:50075"
     - "50475:50475"
     - "50010:50010"
     - "50020:50020"
     - "50030:50030"
     # Solr
     - "8983:8983"
     - "21000:21000"
     - "33389:33389"
  kdc.dev:
    build: ../../../docker-kerberos/kdc-kadmin
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
    networks:
     - dev
    hostname: kdc
    domainname: dev
    ports:
     - "88:88"
  nifi:
    build: ../../../docker-nifi
    hostname: nifi
    domainname: dev
    image: nifi:krb
    ports:
     - "9080:8080"
    networks:
     - dev
networks:
  dev:
    driver: bridge
